### ISSUE TITLE
Framework to build a binding library for xamarin 

### ISSUE THREAD

**Issue by ulrickpsp** [espressif/esp-idf-provisioning-ios#32]
Hi.

I'm working on a Xamarin project that makes use of this library as well as the Android one.

I successfully created the bindings for Android but I'm struggling to achieve the same for iOS.

Would it be possible to create a framework from this library so that I can make the binding library for xamarin ios?

Any help would be appreciated.

**Comment by AjayGantayet** [comment]
Hi @ulrickpsp  there are some challenges w.r.t. binding libraries built in Swift  with Xamarin. It requires some additional steps and configuration to successfully build and run an iOS Xamarin app.
Our project currently does not have the required Objective C header that you would need in order to be able to successfully accomplish the binding. You could go with the following options:
	
- Update the Swift source code to generate the header and mark the required members with @objc attribute
- Build a proxy framework where you control the public interface and proxy all the calls to underlying framework

In order to get more info on this you can go through the following documentation:
https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-swift/walkthrough

**Comment by ulrickpsp** [comment]
Thanks a lot for the tutorial.

Working like a charm altought it's a bit tough the first time you do the process.
