### ISSUE TITLE
peripheralsNotFound

### ISSUE THREAD

**Issue by pradeepktg** [espressif/esp-idf-provisioning-ios#4]
Hi, I'm building an App where I want to provision the esp32 for WIFi. I successfully build the App and chose "BLESec0" Debug as the scheme. When I run the app and scan for the peripheral, the table is not showing any peripherals. I kept breakpoints and it is always coming to the below function. What I'm doing wrong? I followed all the steps, but still no luck. I would also like to know how to provision using WiFi.
Swift - 5
XCode - 10.2.1
SwiftProtobuf - 1.5.0
Curve25519 - 1.1.0
```
func peripheralsNotFound(serviceUUID _: UUID?) {
        showBusy(isBusy: false)
    }
```

**Comment by vikas-chandra-mnnit** [comment]
Hi @pradeepktg ,

It may happen that esp32 device may already have some wifi credentials set on it. 
Do `make erase_flash` followed by `make flash` to clear the credentials from the device. Then start provision again. 
If the above solution doesn't work for you, then please share the device logs so we can look into it with more details.

To provision using wifi you need device with SoftAP app. Then you can select WiFiSec0 or WiFiSec1 as your scheme. Follow the instructions on the app. Let me know if you have further queries.

**Comment by pradeepktg** [comment]
Hi @vikas-chandra-mnnit - Thanks. I tried to delete the wifi credentials set on the esp32 device, but still, the esp32 device is not listing in the tableview. Is there any specific I need to configure?

**Comment by vikas-chandra-mnnit** [comment]
> I didn't understand the below statement and not sure how to change the value.
> 
> > For Security 1, for BLE or Wi-Fi, you can set an optional Proof of Possession key. Make sure that the key present in Example Configuration -> Proof-of-possession under ESP-IDF example menuconfig is the same as the one set in Info.plist file in the ./EspressifProvision/EspressifProvision/ folder

HI @pradeepktg This means that you have to keep proof-of-possession same in phone app as well as device. So that phone app can authenticate itself with the device. This is set during device side configuration and its needed to be same in device and Info.plist file of Xcode project as a value for key "ProofOfPossession". However this happens after the device is discovered.

Can you please send us the monitor log, so that we can better investigate the reason why device is not getting discovered?

**Comment by pradeepktg** [comment]
I have attached the log and video
[ESP32.log](https://github.com/espressif/esp-idf-provisioning-ios/files/3422327/ESP32.log)

I this the file you are looking for? I don't see this particular app log in the Device log in Xcode.

**Comment by pradeepktg** [comment]
@vikas-chandra-mnnit - Did you get a chance to look into the logs?

**Comment by shahpiyushv** [comment]
@pradeepktg , can you provide some more details like
1. IDF version
2. IDF example being used for testing
3. Any specific configuration options set by you

**Comment by pradeepktg** [comment]
@shahpiyushv Hi, I'm using "esp-idf-provisioning-ios". I'm not sure where to see the IDF version and below are the pod version, I have the same version installed on Mac
```
  pod 'SwiftProtobuf', '~> 1.5.0'
  pod 'Curve25519', '~> 1.1.0'
```

**Comment by vikas-chandra-mnnit** [comment]
@pradeepktg We would like to inform you that since your last comment there has been a lot of structural and design changes in our provisioning source. We have created ESPProvision library for iOS which can be integrated into your application using CocoaPods. The library contains all the APIs required to provision both BLE and SoftAP devices. You can find the usage and documentation for the same in README. We have also included a sample app to demonstrate the working of the library. These sample apps are also available on App Store [Link1](https://apps.apple.com/in/app/esp-softap-provisioning/id1474040630)  [Link2](https://apps.apple.com/in/app/esp-ble-provisioning/id1473590141).

We request you to use this library and sample app reference for any development henceforth. We will close this ticket as part of our cleanup process. If you see any issue with the library or any components feel free to open a new ticket for it. Thanks for your support.
