### ISSUE TITLE
compile error SwiftProtobuf

### ISSUE THREAD

**Issue by altercode** [espressif/esp-idf-provisioning-ios#6]
Hi,

xcode version 10.3
macos 10.15.2

I have Swiftprotobuf 1.7.0 installed via hombrew
I have updated podfile in the project

`pod 'SwiftProtobuf', '~> 1.7.0'`

I get Swift Compile Error on SwiftProtobuf

`TextFormatDecoder.swift:33:9: Missing return in a function expected to return 'Bool'`

Strange thing is that when I compile it first time it compile. When I compile in second time (without any change) above error occurs.

Can someone help me with this?

**Comment by vikas-chandra-mnnit** [comment]
@altercode We would like to inform you that since your last comment there has been a lot of structural and design changes in our provisioning source. We have created ESPProvision library for iOS which can be integrated into your application using CocoaPods. The library contains all the APIs required to provision both BLE and SoftAP devices. You can find the usage and documentation for the same in README. We have also included a sample app to demonstrate the working of the library. These sample apps are also available on App Store [Link1](https://apps.apple.com/in/app/esp-softap-provisioning/id1474040630)  [Link2](https://apps.apple.com/in/app/esp-ble-provisioning/id1473590141).

We request you to use this library and sample app reference for any development henceforth. We will close this ticket as part of our cleanup process. If you see any issue with the library or any components feel free to open a new ticket for it. Thanks for your support.
