### ISSUE TITLE
Which release we should use?

### ISSUE THREAD

**Issue by hehao9051** [espressif/esp-idf-provisioning-ios#7]
Hi:
Our project use idf version is V3.2(id:286202caa)，and use example in it, but app download from app store is not work, so we want to know which release we should use?

**Comment by vikas-chandra-mnnit** [comment]
> Hi:
> Our project use idf version is V3.2(id:286202caa)，and use example in it, but app download from app store is not work, so we want to know which release we should use?

Hi,
Please give us information about the app you are using currently and what error you are facing while using the app.

**Comment by hehao9051** [comment]
sorry to be late, we try to watch the log out, but now app can not found the device.(we use other ble debug app can find it). could you try this example ?

**Comment by vikas-chandra-mnnit** [comment]
@hehao9051 We would like to inform you that since your last comment there has been a lot of structural and design changes in our provisioning source. We have created ESPProvision library for iOS which can be integrated into your application using CocoaPods. The library contains all the APIs required to provision both BLE and SoftAP devices. You can find the usage and documentation for the same in README. We have also included a sample app to demonstrate the working of the library. These sample apps are also available on App Store [Link1](https://apps.apple.com/in/app/esp-softap-provisioning/id1474040630)  [Link2](https://apps.apple.com/in/app/esp-ble-provisioning/id1473590141).

We request you to use this library and sample app reference for any development henceforth. We will close this ticket as part of our cleanup process. If you see any issue with the library or any components feel free to open a new ticket for it. Thanks for your support.
